// Cookie工具实现
import { BaseTool } from '../base-tool.js';
import { TOOL_TYPES } from '../../utils/constants.js';

export class CookieTool extends BaseTool {
  constructor() {
    super('Cookie Tool', TOOL_TYPES.COOKIE);

    this.name = '获取当前网页cookie';
    this.description = '点击直接复制当前页面的Cookie';
    this.icon = '🍪';

    this.cookies = [];
    this.element = null;
    this.currentFormat = 'header'; // 'header' | 'netscape'

    // 创建DOM元素
    this.createElement();
  }

  createElement() {
    this.element = document.createElement('div');
    this.element.className = 'cookie-tool';
    this.element.innerHTML = `
      <div class="tool-controls">
        <button id="fetch-and-copy" class="primary-button">获取并复制Cookie</button>
      </div>

      <div class="format-selector">
        <span class="format-label">输出格式：</span>
        <label class="format-option">
          <input type="radio" name="cookie-format" value="header" checked>
          <span>Header String</span>
        </label>
        <label class="format-option">
          <input type="radio" name="cookie-format" value="netscape">
          <span>Netscape</span>
        </label>
      </div>

      <div id="cookie-loading" class="loading hidden">
        <span>正在获取Cookie...</span>
      </div>

      <div id="cookie-message" class="cookie-message hidden"></div>

      <div id="cookie-error" class="error-message hidden">
        <p>获取Cookie失败</p>
        <p id="error-details" class="error-details"></p>
      </div>
    `;

    this.setupEventListeners();
  }

  setupEventListeners() {
    const button = this.element.querySelector('#fetch-and-copy');
    button.addEventListener('click', () => this.fetchAndCopyCookies());

    // 格式选择
    const formatRadios = this.element.querySelectorAll('input[name="cookie-format"]');
    formatRadios.forEach(radio => {
      radio.addEventListener('change', (e) => {
        this.currentFormat = e.target.value;
      });
    });
  }

  /**
   * 转换为 Header String 格式
   * 格式: name1=value1; name2=value2
   */
  formatAsHeaderString(cookies) {
    return cookies.map(cookie => `${cookie.name}=${cookie.value}`).join('; ');
  }

  /**
   * 转换为 Netscape cookie file 格式
   * 格式: domain\tflag\tpath\tsecure\texpiration\tname\tvalue
   *
   * Netscape 格式说明：
   * - domain: cookie所属的域名
   * - flag: TRUE 表示 domain 包含子域名，FALSE 表示不包含
   * - path: 路径，通常为/
   * - secure: 是否仅HTTPS传输（TRUE/FALSE）
   * - expiration: 过期时间（Unix时间戳），0表示会话cookie
   * - name: cookie名称
   * - value: cookie值
   */
  formatAsNetscape(cookies, url) {
    const urlObj = new URL(url);

    // Netscape 格式标准文件头
    const header = '# Netscape HTTP Cookie File\n' +
                   '# Generated by ToolBox Pro\n' +
                   '# https://github.com/icefrag/Tool_Box_Pro\n' +
                   '# domain\tflag\tpath\tsecure\texpiration\tname\tvalue\n';

    const lines = cookies.map(cookie => {
      const domain = cookie.domain || urlObj.hostname;
      // flag: TRUE 表示 domain 包含子域名（以 . 开头）
      const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE';
      const path = cookie.path || '/';
      const secure = cookie.secure ? 'TRUE' : 'FALSE';
      // session cookie 没有 expiration，使用 0
      const expiration = cookie.session ? '0' : String(Math.floor(cookie.expirationDate || 0));

      return `${domain}\t${flag}\t${path}\t${secure}\t${expiration}\t${cookie.name}\t${cookie.value}`;
    });

    return header + lines.join('\n');
  }

  async initialize() {
    this.log('Cookie工具初始化完成');
    this.resetUI();
  }

  resetUI() {
    if (!this.element) return;

    const messageEl = this.element.querySelector('#cookie-message');
    const errorEl = this.element.querySelector('#cookie-error');
    const loadingEl = this.element.querySelector('#cookie-loading');

    messageEl?.classList.add('hidden');
    errorEl?.classList.add('hidden');
    loadingEl?.classList.add('hidden');

    this.cookies = [];
  }

  async fetchAndCopyCookies() {
    this.resetUI();
    if (this.element) {
      this.element.querySelector('#cookie-loading')?.classList.remove('hidden');
    }

    try {
      const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });

      if (!tab) {
        throw new Error('未找到活动标签页');
      }

      const url = new URL(tab.url);
      this.cookies = await chrome.cookies.getAll({ url: url.href });

      if (this.element) {
        this.element.querySelector('#cookie-loading')?.classList.add('hidden');
      }

      if (this.cookies.length === 0) {
        this.showMessage('当前页面没有Cookie');
        return { success: false, message: '当前页面没有Cookie' };
      }

      // 根据选择的格式生成 cookie 字符串
      let cookieString;
      let formatName;
      if (this.currentFormat === 'netscape') {
        cookieString = this.formatAsNetscape(this.cookies, tab.url);
        formatName = 'Netscape';
      } else {
        cookieString = this.formatAsHeaderString(this.cookies);
        formatName = 'Header String';
      }

      await navigator.clipboard.writeText(cookieString);

      const message = `已复制 ${this.cookies.length} 个Cookie到剪贴板 (${formatName}格式)`;
      this.showMessage(message);
      this.log(`从${url.hostname}获取到${this.cookies.length}个Cookie并已复制`);

      return { success: true, message };
    } catch (error) {
      this.showError(`获取Cookie失败: ${error.message}`);
      const message = error.message || '未知错误';
      if (this.element) {
        const loadingEl = this.element.querySelector('#cookie-loading');
        const errorEl = this.element.querySelector('#cookie-error');
        const errorDetailsEl = this.element.querySelector('#error-details');
        loadingEl?.classList.add('hidden');
        errorEl?.classList.remove('hidden');
        if (errorDetailsEl) errorDetailsEl.textContent = message;
      }
      return { success: false, message: '获取Cookie失败: ' + message };
    }
  }

  showMessage(text) {
    if (!this.element) return;
    const messageEl = this.element.querySelector('#cookie-message');
    if (messageEl) {
      messageEl.textContent = text;
      messageEl.classList.remove('hidden');
    }
  }

  async execute() {
    return this.fetchAndCopyCookies();
  }

  async destroy() {
    this.log('Cookie工具已销毁');
    this.resetUI();
    this.element = null;
    this.cookies = [];
  }
}
